source 'gogs@git.qupeiyin.net:FeiZhu_IOS_Pub_Repo/FZSpecs.git'
source 'https://cdn.cocoapods.org/'


use_frameworks!

platform :ios, '9.0'

target 'ModuleA_Example' do
  pod 'ModuleA', :path => '../'
  target 'ModuleA_Tests' do
    inherit! :search_paths

    
  end
end
